services:
  - type: web
    name: ruby-pubmed-secure
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /login
    autoDeploy: true
    regions:
      - oregon
    scaling:
      minInstances: 1
      maxInstances: 1
